<?php

/**
 * @file
 * Provides custom extensions for the DDD Views feature.
 */

declare(strict_types=1);

/**
 * Implements hook_views_data_alter().
 */
function ddd_views_views_data_alter(array &$data) {
  $data['node_field_data']['natural_title_sort'] = [
    'title' => t('Natural title sort'),
    'group' => t('Content'),
    'help' => t('Sort titles naturally'),
    'sort' => [
      'field' => 'title',
      'id' => 'natural_title_sort',
    ],
  ];
}
