version: '2'
services:
  web:
    image: fpfis/httpd-php-dev:8.1
#    image: fpfis/httpd-php:8.1-ci
    working_dir: ${PWD}
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:${PWD}
      # - $HOME/.composer/.auth.json:$HOME/.composer/.auth.json
    environment:
      DOCUMENT_ROOT: ${PWD}
      # By leaving these variables empty Docker Compose will set them to their host values.
      NEXTCLOUD_USER:
      NEXTCLOUD_PASS:
      GITHUB_API_TOKEN:
      GITLAB_API_TOKEN:
      QA_API_BASIC_AUTH:
      QA_WEBSITE_URL:
      # XDEBUG CONFIGURATION.
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
      PHP_IDE_CONFIG: "serverName=Docker"
      DRUPAL_FLUSH_CREDS: "flush:test"
      DRUPAL_SITE_NAME: "ddd"
      DRUPAL_ENVIRONMENT: "local"
      DRUPAL_DATABASE_USERNAME: root
      DRUPAL_DATABASE_PASSWORD:
      DRUPAL_DATABASE_PREFIX:
      DRUPAL_DATABASE_NAME: tdd
      DRUPAL_DATABASE_HOST: mysql
      DRUPAL_DATABASE_PORT: 3306
      DRUPAL_ACCOUNT_USERNAME: admin
      DRUPAL_ACCOUNT_PASSWORD: admin
      DRUPAL_ACCOUNT_EMAIL: abel.santos-corral@ext.ec.europa.eu
      DRUPAL_BASE_URL: http://web:8080/web
      VIRTUAL_HOST: http://web:8080/web
      DRUSH_OPTIONS_URI: http://web:8080/web
      # For Xdebug setup, run this command in the terminal:
      # For Mac users: sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
      # For Linux users: sudo ip addr add 10.254.254.254/32 dev lo label lo:1

  mysql:
    image: percona/percona-server:5.7
    command: --innodb-log-file_size=2G --max-allowed-packet=1G --innodb-buffer-pool-size=512M --wait-timeout=31536000
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  selenium:
    image: selenium/standalone-chrome:4.1.3-20220405
    environment:
      - DISPLAY=:99
    ports:
      - "5900:5900"
    expose:
      - 4444

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    # restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD:

volumes:
  mysql:
