<?php

/**
 * @file
 * Provides custom extensions for the DDD Search feature.
 */

declare(strict_types=1);

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_query_alter().
 */
function ddd_search_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() === 'search_content') {
    // Look for an ?keys={VALUE} query string in the URL.
    $keys = \Drupal::request()->query->get('keys');

    if (!isset($keys) || empty($keys)) {
      /** @var \Drupal\search_api\Plugin\views\query\SearchApiQuery $query */
      $query->sort('sticky', 'DESC');
      $query->sort('created', 'DESC');
    }
  }

  // Not sure if this is an instance of \Drupal\views\Plugin\views\query\Sql or
  // something else? Use get_class() to find out.
  # echo get_class($query);
}
